nodes:
- id: n_0_0_N
  row: 0
  col: 0
  dir: N
  x: -1.4
  y: -1.4
  yaw: 1.5708
  stop: false
  kind: corner_in
  in_dir: W
  index: 33
- id: n_0_0_E
  row: 0
  col: 0
  dir: E
  x: -1.8
  y: -1.8
  yaw: 0.0
  stop: false
  kind: corner_out
  in_dir: S
  index: 13
- id: n_0_1_E
  row: 0
  col: 1
  dir: E
  x: -0.8
  y: -1.8
  yaw: 0.0
  stop: false
  kind: straight
  in_dir: null
  index: 14
- id: n_0_1_W
  row: 0
  col: 1
  dir: W
  x: -0.8
  y: -1.4
  yaw: 3.1416
  stop: false
  kind: straight
  in_dir: null
  index: 32
- id: n_0_2_E
  row: 0
  col: 2
  dir: E
  x: 0.0
  y: -1.8
  yaw: 0.0
  stop: false
  kind: t_junction
  in_dir: null
  index: 15
- id: n_0_2_W
  row: 0
  col: 2
  dir: W
  x: 0.0
  y: -1.4
  yaw: 3.1416
  stop: false
  kind: t_junction
  in_dir: null
  index: 31
- id: n_0_3_E
  row: 0
  col: 3
  dir: E
  x: 0.8
  y: -1.8
  yaw: 0.0
  stop: false
  kind: straight
  in_dir: null
  index: 16
- id: n_0_3_W
  row: 0
  col: 3
  dir: W
  x: 0.8
  y: -1.4
  yaw: 3.1416
  stop: false
  kind: straight
  in_dir: null
  index: 30
- id: n_0_4_N
  row: 0
  col: 4
  dir: N
  x: 1.8
  y: -1.8
  yaw: 1.5708
  stop: false
  kind: corner_out
  in_dir: E
  index: 1
- id: n_0_4_W
  row: 0
  col: 4
  dir: W
  x: 1.4
  y: -1.4
  yaw: 3.1416
  stop: false
  kind: corner_in
  in_dir: S
  index: 29
- id: n_1_0_N
  row: 1
  col: 0
  dir: N
  x: -1.4
  y: -0.8
  yaw: 1.5708
  stop: false
  kind: straight
  in_dir: null
  index: 34
- id: n_1_0_S
  row: 1
  col: 0
  dir: S
  x: -1.8
  y: -0.8
  yaw: -1.5708
  stop: false
  kind: straight
  in_dir: null
  index: 12
- id: n_1_2_N
  row: 1
  col: 2
  dir: N
  x: 0.2
  y: -0.8
  yaw: 1.5708
  stop: false
  kind: straight
  in_dir: null
  index: 17
- id: n_1_2_S
  row: 1
  col: 2
  dir: S
  x: -0.2
  y: -0.8
  yaw: -1.5708
  stop: false
  kind: straight
  in_dir: null
  index: 39
- id: n_1_4_N
  row: 1
  col: 4
  dir: N
  x: 1.8
  y: -0.8
  yaw: 1.5708
  stop: false
  kind: straight
  in_dir: null
  index: 2
- id: n_1_4_S
  row: 1
  col: 4
  dir: S
  x: 1.4
  y: -0.8
  yaw: -1.5708
  stop: false
  kind: straight
  in_dir: null
  index: 28
- id: n_2_0_N
  row: 2
  col: 0
  dir: N
  x: -1.4
  y: 0.0
  yaw: 1.5708
  stop: false
  kind: t_junction
  in_dir: null
  index: 35
- id: n_2_0_S
  row: 2
  col: 0
  dir: S
  x: -1.8
  y: 0.0
  yaw: -1.5708
  stop: false
  kind: t_junction
  in_dir: null
  index: 11
- id: n_2_1_E
  row: 2
  col: 1
  dir: E
  x: -0.8
  y: -0.2
  yaw: 0.0
  stop: false
  kind: straight
  in_dir: null
  index: 36
- id: n_2_1_W
  row: 2
  col: 1
  dir: W
  x: -0.8
  y: 0.2
  yaw: 3.1416
  stop: false
  kind: straight
  in_dir: null
  index: 19
- id: n_2_2_X
  row: 2
  col: 2
  dir: X
  x: 0.0
  y: 0.0
  yaw: 0.0
  stop: false
  kind: intersection
  in_dir: null
  index: 18
- id: n_2_3_E
  row: 2
  col: 3
  dir: E
  x: 0.8
  y: -0.2
  yaw: 0.0
  stop: false
  kind: straight
  in_dir: null
  index: 40
- id: n_2_3_W
  row: 2
  col: 3
  dir: W
  x: 0.8
  y: 0.2
  yaw: 3.1416
  stop: false
  kind: straight
  in_dir: null
  index: 37
- id: n_2_4_N
  row: 2
  col: 4
  dir: N
  x: 1.8
  y: 0.0
  yaw: 1.5708
  stop: false
  kind: t_junction
  in_dir: null
  index: 3
- id: n_2_4_S
  row: 2
  col: 4
  dir: S
  x: 1.4
  y: 0.0
  yaw: -1.5708
  stop: false
  kind: t_junction
  in_dir: null
  index: 27
- id: n_3_0_N
  row: 3
  col: 0
  dir: N
  x: -1.4
  y: 0.8
  yaw: 1.5708
  stop: false
  kind: straight
  in_dir: null
  index: 20
- id: n_3_0_S
  row: 3
  col: 0
  dir: S
  x: -1.8
  y: 0.8
  yaw: -1.5708
  stop: false
  kind: straight
  in_dir: null
  index: 10
- id: n_3_2_N
  row: 3
  col: 2
  dir: N
  x: 0.2
  y: 0.8
  yaw: 1.5708
  stop: false
  kind: straight
  in_dir: null
  index: 41
- id: n_3_2_S
  row: 3
  col: 2
  dir: S
  x: -0.2
  y: 0.8
  yaw: -1.5708
  stop: false
  kind: straight
  in_dir: null
  index: 38
- id: n_3_4_N
  row: 3
  col: 4
  dir: N
  x: 1.8
  y: 0.8
  yaw: 1.5708
  stop: false
  kind: straight
  in_dir: null
  index: 4
- id: n_3_4_S
  row: 3
  col: 4
  dir: S
  x: 1.4
  y: 0.8
  yaw: -1.5708
  stop: false
  kind: straight
  in_dir: null
  index: 26
- id: n_4_0_S
  row: 4
  col: 0
  dir: S
  x: -1.8
  y: 1.8
  yaw: -1.5708
  stop: false
  kind: corner_out
  in_dir: W
  index: 9
- id: n_4_0_E
  row: 4
  col: 0
  dir: E
  x: -1.4
  y: 1.4
  yaw: 0.0
  stop: false
  kind: corner_in
  in_dir: N
  index: 21
- id: n_4_1_E
  row: 4
  col: 1
  dir: E
  x: -0.8
  y: 1.4
  yaw: 0.0
  stop: false
  kind: straight
  in_dir: null
  index: 22
- id: n_4_1_W
  row: 4
  col: 1
  dir: W
  x: -0.8
  y: 1.8
  yaw: 3.1416
  stop: false
  kind: straight
  in_dir: null
  index: 8
- id: n_4_2_E
  row: 4
  col: 2
  dir: E
  x: 0.0
  y: 1.4
  yaw: 0.0
  stop: false
  kind: t_junction
  in_dir: null
  index: 23
- id: n_4_2_W
  row: 4
  col: 2
  dir: W
  x: 0.0
  y: 1.8
  yaw: 3.1416
  stop: false
  kind: t_junction
  in_dir: null
  index: 7
- id: n_4_3_E
  row: 4
  col: 3
  dir: E
  x: 0.8
  y: 1.4
  yaw: 0.0
  stop: false
  kind: straight
  in_dir: null
  index: 24
- id: n_4_3_W
  row: 4
  col: 3
  dir: W
  x: 0.8
  y: 1.8
  yaw: 3.1416
  stop: false
  kind: straight
  in_dir: null
  index: 6
- id: n_4_4_S
  row: 4
  col: 4
  dir: S
  x: 1.4
  y: 1.4
  yaw: -1.5708
  stop: false
  kind: corner_in
  in_dir: E
  index: 25
- id: n_4_4_W
  row: 4
  col: 4
  dir: W
  x: 1.8
  y: 1.8
  yaw: 3.1416
  stop: false
  kind: corner_out
  in_dir: N
  index: 5
edges:
- src: n_0_0_N
  dst: n_1_0_N
  cost: 0.6
  kind: straight
  enabled: true
- src: n_0_0_E
  dst: n_0_1_E
  cost: 1.0
  kind: straight
  enabled: true
- src: n_0_1_E
  dst: n_0_2_E
  cost: 0.8
  kind: straight
  enabled: true
- src: n_0_1_W
  dst: n_0_0_N
  cost: 0.9
  kind: right
  enabled: true
- src: n_0_2_E
  dst: n_0_3_E
  cost: 0.8
  kind: straight
  enabled: true
- src: n_0_2_E
  dst: n_1_2_N
  cost: 1.53
  kind: left
  enabled: true
- src: n_0_2_W
  dst: n_0_1_W
  cost: 0.8
  kind: straight
  enabled: true
- src: n_0_3_E
  dst: n_0_4_N
  cost: 1.5
  kind: left
  enabled: true
- src: n_0_3_W
  dst: n_0_2_W
  cost: 0.8
  kind: straight
  enabled: true
- src: n_0_4_N
  dst: n_1_4_N
  cost: 1.0
  kind: straight
  enabled: true
- src: n_0_4_W
  dst: n_0_3_W
  cost: 0.6
  kind: straight
  enabled: true
- src: n_1_0_N
  dst: n_2_0_N
  cost: 0.8
  kind: straight
  enabled: true
- src: n_1_0_S
  dst: n_0_0_E
  cost: 1.5
  kind: left
  enabled: true
- src: n_1_2_N
  dst: n_2_2_X
  cost: 0.825
  kind: straight
  enabled: true
- src: n_1_2_S
  dst: n_0_2_E
  cost: 1.53
  kind: left
  enabled: true
- src: n_1_4_N
  dst: n_2_4_N
  cost: 0.8
  kind: straight
  enabled: true
- src: n_1_4_S
  dst: n_0_4_W
  cost: 0.9
  kind: right
  enabled: true
- src: n_2_0_N
  dst: n_3_0_N
  cost: 0.8
  kind: straight
  enabled: true
- src: n_2_0_S
  dst: n_1_0_S
  cost: 0.8
  kind: straight
  enabled: true
- src: n_2_0_S
  dst: n_2_1_E
  cost: 1.53
  kind: left
  enabled: true
- src: n_2_1_E
  dst: n_2_2_X
  cost: 0.825
  kind: straight
  enabled: true
- src: n_2_1_W
  dst: n_2_0_S
  cost: 1.53
  kind: left
  enabled: true
- src: n_2_2_X
  dst: n_3_2_N
  cost: 0.825
  kind: straight
  enabled: true
- src: n_2_2_X
  dst: n_1_2_S
  cost: 0.825
  kind: straight
  enabled: true
- src: n_2_2_X
  dst: n_2_3_E
  cost: 0.825
  kind: straight
  enabled: true
- src: n_2_2_X
  dst: n_2_1_W
  cost: 0.825
  kind: straight
  enabled: true
- src: n_2_3_E
  dst: n_2_4_N
  cost: 1.53
  kind: left
  enabled: true
- src: n_2_3_W
  dst: n_2_2_X
  cost: 0.825
  kind: straight
  enabled: true
- src: n_2_4_N
  dst: n_3_4_N
  cost: 0.8
  kind: straight
  enabled: true
- src: n_2_4_N
  dst: n_2_3_W
  cost: 1.53
  kind: left
  enabled: true
- src: n_2_4_S
  dst: n_1_4_S
  cost: 0.8
  kind: straight
  enabled: true
- src: n_3_0_N
  dst: n_4_0_E
  cost: 0.9
  kind: right
  enabled: true
- src: n_3_0_S
  dst: n_2_0_S
  cost: 0.8
  kind: straight
  enabled: true
- src: n_3_2_N
  dst: n_4_2_W
  cost: 1.53
  kind: left
  enabled: true
- src: n_3_2_S
  dst: n_2_2_X
  cost: 0.825
  kind: straight
  enabled: true
- src: n_3_4_N
  dst: n_4_4_W
  cost: 1.5
  kind: left
  enabled: true
- src: n_3_4_S
  dst: n_2_4_S
  cost: 0.8
  kind: straight
  enabled: true
- src: n_4_0_S
  dst: n_3_0_S
  cost: 1.0
  kind: straight
  enabled: true
- src: n_4_0_E
  dst: n_4_1_E
  cost: 0.6
  kind: straight
  enabled: true
- src: n_4_1_E
  dst: n_4_2_E
  cost: 0.8
  kind: straight
  enabled: true
- src: n_4_1_W
  dst: n_4_0_S
  cost: 1.5
  kind: left
  enabled: true
- src: n_4_2_E
  dst: n_4_3_E
  cost: 0.8
  kind: straight
  enabled: true
- src: n_4_2_W
  dst: n_4_1_W
  cost: 0.8
  kind: straight
  enabled: true
- src: n_4_2_W
  dst: n_3_2_S
  cost: 1.53
  kind: left
  enabled: true
- src: n_4_3_E
  dst: n_4_4_S
  cost: 0.9
  kind: right
  enabled: true
- src: n_4_3_W
  dst: n_4_2_W
  cost: 0.8
  kind: straight
  enabled: true
- src: n_4_4_S
  dst: n_3_4_S
  cost: 0.6
  kind: straight
  enabled: true
- src: n_4_4_W
  dst: n_4_3_W
  cost: 1.0
  kind: straight
  enabled: true
- src: n_3_4_S
  dst: n_2_3_W
  cost: 1.273
  kind: right
  enabled: true
- src: n_2_3_E
  dst: n_1_4_S
  cost: 1.273
  kind: right
  enabled: true
- src: n_1_2_S
  dst: n_0_1_W
  cost: 1.273
  kind: right
  enabled: true
- src: n_0_3_W
  dst: n_1_2_N
  cost: 1.273
  kind: right
  enabled: true
- src: n_1_0_N
  dst: n_2_1_E
  cost: 1.273
  kind: right
  enabled: true
- src: n_2_1_W
  dst: n_3_0_N
  cost: 1.273
  kind: right
  enabled: true
- src: n_3_2_N
  dst: n_4_3_E
  cost: 1.273
  kind: right
  enabled: true
- src: n_4_1_E
  dst: n_3_2_S
  cost: 1.273
  kind: right
  enabled: true
